#!/usr/bin/env bash

set -euo pipefail
export LC_ALL=C

usage() {
    cat >&2 <<'EOF'
Usage:
  render-diagrams.sh [--check] [--png] models/TM-YYYYMMDD-NNN-short-name

SVG is always generated or checked. --png also enables PNG derivatives.
An existing diagrams/png directory keeps PNG rendering and checking enabled.
EOF
}

die() {
    printf 'render-diagrams: ERROR: %s\n' "$*" >&2
    exit 1
}

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P) ||
    die "cannot resolve repository root"
cd -- "$repository_root"

check=false
png=false
while (($# > 0)); do
    case $1 in
    --check)
        if $check; then
            usage
            exit 2
        fi
        check=true
        shift
        ;;
    --png)
        if $png; then
            usage
            exit 2
        fi
        png=true
        shift
        ;;
    --*)
        usage
        exit 2
        ;;
    *)
        break
        ;;
    esac
done
(($# == 1)) || {
    usage
    exit 2
}

package=$1
[[ $package =~ ^models/TM-[0-9]{8}-[0-9]{3}-[a-z0-9]+(-[a-z0-9]+)*$ ]] ||
    die "package path must be a repository-relative TM package"
[[ -d $package/diagrams ]] || die "diagram directory is missing: $package"
command -v dot >/dev/null 2>&1 || die "Graphviz dot is unavailable"

resolved=$(CDPATH= cd -- "$package" && pwd -P) ||
    die "cannot resolve package"
case $resolved in
"$repository_root"/models/*) ;;
*) die "package escapes the repository" ;;
esac

png_directory=$package/diagrams/png
if [[ -e $png_directory || -L $png_directory ]]; then
    [[ -d $png_directory && ! -L $png_directory ]] ||
        die "PNG output directory must be an ordinary directory: $png_directory"
    png=true
fi

formats=(svg)
if $png; then
    formats+=(png)
fi
for format in "${formats[@]}"; do
    directory=$package/diagrams/$format
    [[ ! -L $directory && ( ! -e $directory || -d $directory ) ]] ||
        die "output directory must be an ordinary directory: $directory"
done

render_output() {
    local format=$1 source=$2
    if [[ $format == svg ]]; then
        dot -Tsvg "$source" | sed '/Generated by graphviz version/d'
    else
        dot -Tpng "$source"
    fi
}

found=false
stale=false
while IFS= read -r -d '' source; do
    found=true
    relative=${source#"$package/diagrams/"}
    for format in "${formats[@]}"; do
        target=$package/diagrams/$format/${relative%.dot}.$format
        [[ ! -L $target && ( ! -e $target || -f $target ) ]] ||
            die "output must be a regular file: $target"
        temporary=$(mktemp "${TMPDIR:-/tmp}/threat-diagram.XXXXXX.$format") ||
            die "cannot create temporary $format"
        if ! render_output "$format" "$source" >"$temporary"; then
            rm -f -- "$temporary"
            die "Graphviz failed for $source ($format)"
        fi
        if [[ ! -s $temporary ]]; then
            rm -f -- "$temporary"
            die "Graphviz produced empty output for $source ($format)"
        fi
        if $check; then
            if [[ ! -f $target ]] || ! cmp -s -- "$temporary" "$target"; then
                printf 'render-diagrams: stale or missing: %s\n' "$target" >&2
                stale=true
            fi
            rm -f -- "$temporary"
        else
            mkdir -p -- "${target%/*}"
            mv -T -- "$temporary" "$target"
            printf 'rendered %s\n' "$target"
        fi
    done
done < <(find "$package/diagrams" -type f -name '*.dot' -print0 | sort -z)

$found || die "no DOT sources were found"
if $stale; then
    exit 1
fi
