#!/usr/bin/env bash

set -euo pipefail
export LC_ALL=C

usage() {
    cat >&2 <<'EOF'
Usage:
  render-diagrams.sh [--check] models/TM-YYYYMMDD-NNN-short-name
EOF
}

die() {
    printf 'render-diagrams: ERROR: %s\n' "$*" >&2
    exit 1
}

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P) ||
    die "cannot resolve repository root"
cd -- "$repository_root"

check=false
if (($# > 0)) && [[ $1 == --check ]]; then
    check=true
    shift
fi
(($# == 1)) || {
    usage
    exit 2
}

package=$1
[[ $package =~ ^models/TM-[0-9]{8}-[0-9]{3}-[a-z0-9]+(-[a-z0-9]+)*$ ]] ||
    die "package path must be a repository-relative TM package"
[[ -d $package/diagrams ]] || die "diagram directory is missing: $package"
command -v dot >/dev/null 2>&1 || die "Graphviz dot is unavailable"

resolved=$(CDPATH= cd -- "$package" && pwd -P) ||
    die "cannot resolve package"
case $resolved in
"$repository_root"/models/*) ;;
*) die "package escapes the repository" ;;
esac

found=false
stale=false
while IFS= read -r -d '' source; do
    found=true
    relative=${source#"$package/diagrams/"}
    target=$package/diagrams/svg/${relative%.dot}.svg
    mkdir -p -- "${target%/*}"
    temporary=$(mktemp "${TMPDIR:-/tmp}/threat-diagram.XXXXXX.svg") ||
        die "cannot create temporary SVG"
    if ! dot -Tsvg "$source" |
        sed '/Generated by graphviz version/d' >"$temporary"; then
        rm -f -- "$temporary"
        die "Graphviz failed for $source"
    fi
    if $check; then
        if [[ ! -f $target ]] || ! cmp -s -- "$temporary" "$target"; then
            printf 'render-diagrams: stale or missing: %s\n' "$target" >&2
            stale=true
        fi
        rm -f -- "$temporary"
    else
        mv -- "$temporary" "$target"
        printf 'rendered %s\n' "$target"
    fi
done < <(find "$package/diagrams" -type f -name '*.dot' -print0 | sort -z)

$found || die "no DOT sources were found"
if $stale; then
    exit 1
fi
