#!/usr/bin/env bash

set -euo pipefail
export LC_ALL=C

usage() {
    cat >&2 <<'EOF'
Usage:
  update-index.sh [--check]
EOF
}

die() {
    printf 'update-index: ERROR: %s\n' "$*" >&2
    exit 1
}

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P) ||
    die "cannot resolve repository root"
cd -- "$repository_root"

check=false
if (($# == 1)) && [[ $1 == --check ]]; then
    check=true
elif (($# != 0)); then
    usage
    exit 2
fi

temporary=$(mktemp "${TMPDIR:-/tmp}/threat-model-index.XXXXXX") ||
    die "cannot create temporary index"
cleanup() {
    rm -f -- "$temporary"
}
trap cleanup EXIT

{
    printf '<!-- Generated by scripts/update-index.sh. Do not edit by hand. -->\n\n'
    printf '# Threat models\n\n'
    shopt -s nullglob
    packages=(models/TM-*)
    shopt -u nullglob
    if ((${#packages[@]} == 0)); then
        printf 'No threat-model package has been created.\n'
    else
        printf '| Package | Title | Created | Mode | Status | Distribution | Latest model | Latest review |\n'
        printf '| --- | --- | --- | --- | --- | --- | --- | --- |\n'
        for package in "${packages[@]}"; do
            scope=$package/scope.md
            [[ -f $scope ]] || die "package is missing scope.md: $package"
            id=$(sed -n 's/^Package ID: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            title=$(sed -n 's/^Title: //p' "$scope" | head -n 1)
            created=$(sed -n 's/^Created: //p' "$scope" | head -n 1)
            mode=$(sed -n 's/^Mode: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            status=$(sed -n 's/^Status: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            distribution=$(sed -n 's/^Distribution: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            model=$(sed -n 's/^Latest model iteration: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            review=$(sed -n 's/^Latest review iteration: `\([^`]*\)`$/\1/p' "$scope" | head -n 1)
            [[ -n $id && -n $title && -n $created && -n $mode &&
                -n $status && -n $distribution && -n $model && -n $review ]] ||
                die "scope metadata is incomplete: $scope"
            printf '| [%s](%s/threat-model.md) | %s | %s | `%s` | `%s` | `%s` | `%s` | `%s` |\n' \
                "$id" "$package" "$title" "$created" "$mode" "$status" \
                "$distribution" "$model" "$review"
        done
    fi
} >"$temporary"

if $check; then
    [[ -f THREAT-MODELS.md ]] || die "THREAT-MODELS.md is missing"
    cmp -s -- "$temporary" THREAT-MODELS.md ||
        die "THREAT-MODELS.md is stale; run scripts/update-index.sh"
else
    mv -- "$temporary" THREAT-MODELS.md
    trap - EXIT
    printf 'updated THREAT-MODELS.md\n'
fi
